"""add fk constraint to events.support_id

Revision ID: 0d2e91541e69
Revises: fdae63fe7d96
Create Date: 2026-04-25 15:31:54.510678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d2e91541e69'
down_revision: Union[str, None] = 'fdae63fe7d96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'events', 'collaborators', ['support_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    # ### end Alembic commands ###