"""adjust initial tables

Revision ID: 103151840ef4
Revises: 5533e9b20614
Create Date: 2026-03-27 14:34:06.548493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '103151840ef4'
down_revision: Union[str, None] = '5533e9b20614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('clients', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_column('clients', 'status')
    op.add_column('contracts', sa.Column('deposit_received', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('contracts', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('contracts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('events', sa.Column('location_street', sa.String(length=255), nullable=True))
    op.add_column('events', sa.Column('location_zip', sa.String(length=20), nullable=True))
    op.add_column('events', sa.Column('location_city', sa.String(length=100), nullable=True))
    op.add_column('events', sa.Column('location_country', sa.String(length=100), server_default='France', nullable=True))
    op.add_column('events', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('events', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.execute("UPDATE events SET attendees = 0 WHERE attendees IS NULL")
    op.alter_column('events', 'attendees',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=False)
    op.drop_column('events', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('events', 'attendees',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('events', 'updated_at')
    op.drop_column('events', 'created_at')
    op.drop_column('events', 'location_country')
    op.drop_column('events', 'location_city')
    op.drop_column('events', 'location_zip')
    op.drop_column('events', 'location_street')
    op.alter_column('contracts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('contracts', 'updated_at')
    op.drop_column('contracts', 'deposit_received')
    op.add_column('clients', sa.Column('status', postgresql.ENUM('PROSPECT', 'IN_NEGOTIATION', 'PENDING_SIGNATURE', 'ACTIVE', 'IN_SUPPORT', 'COMPLETED', 'INACTIVE', name='clientstatus'), server_default=sa.text("'PROSPECT'::clientstatus"), autoincrement=False, nullable=False))
    op.alter_column('clients', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('clients', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###