"""add fk collaborators to contracts commercial_id

Revision ID: 14ba081eb5af
Revises: 1e00091dd6b3
Create Date: 2026-04-01 15:38:30.728279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14ba081eb5af'
down_revision: Union[str, None] = '1e00091dd6b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'contracts', 'collaborators', ['commercial_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    # ### end Alembic commands ###