"""remove server_default from contract status

Revision ID: 1e00091dd6b3
Revises: 0055c8c10957
Create Date: 2026-03-29 19:27:58.198628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e00091dd6b3'
down_revision: Union[str, None] = '0055c8c10957'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###