"""add fk collaborators to clients and contracts commercial_id

Revision ID: b90bda1a1531
Revises: 14ba081eb5af
Create Date: 2026-04-01 15:40:26.077864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b90bda1a1531'
down_revision: Union[str, None] = '14ba081eb5af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'clients', 'collaborators', ['commercial_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='foreignkey')
    # ### end Alembic commands ###